import { ProjectFile } from './types';

/**
 * Full-stack project template: React + Vite (frontend) + Express (backend)
 * Uses npm workspaces with concurrently to run both servers.
 */

function rootPackageJson(): string {
  return JSON.stringify({
    name: 'generated-fullstack-app',
    private: true,
    version: '0.0.1',
    type: 'module',
    scripts: {
      dev: 'concurrently "npm run dev:frontend" "npm run dev:backend"',
      'dev:frontend': 'npm run dev --workspace=frontend',
      'dev:backend': 'node backend/server.js',
    },
    devDependencies: {
      concurrently: '^9.1.0',
    },
  }, null, 2);
}

function frontendPackageJson(): string {
  return JSON.stringify({
    name: 'frontend',
    private: true,
    version: '0.0.1',
    type: 'module',
    scripts: {
      dev: 'vite --host 0.0.0.0 --port $PORT',
      build: 'vite build',
    },
    dependencies: {
      react: '^18.3.1',
      'react-dom': '^18.3.1',
      'lucide-react': '^0.468.0',
    },
    devDependencies: {
      '@vitejs/plugin-react': '^4.3.4',
      vite: '^6.0.0',
      '@tailwindcss/vite': '^4.0.0',
      tailwindcss: '^4.0.0',
    },
  }, null, 2);
}

function viteConfig(port: number, backendPort: number): string {
  return `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
  plugins: [react(), tailwindcss()],
  server: {
    host: '0.0.0.0',
    port: ${port},
    proxy: {
      '/api': {
        target: 'http://localhost:${backendPort}',
        changeOrigin: true,
      },
    },
  },
});
`;
}

function indexHtml(): string {
  return `<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`;
}

function mainJsx(): string {
  return `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
`;
}

const indexCss = `@import "tailwindcss";
`;

function backendPackageJson(): string {
  return JSON.stringify({
    name: 'backend',
    private: true,
    version: '0.0.1',
    type: 'module',
    scripts: {
      dev: 'node server.js',
    },
    dependencies: {
      express: '^4.21.0',
      cors: '^2.8.5',
    },
  }, null, 2);
}

function backendServerJs(port: number): string {
  return `import express from 'express';
import cors from 'cors';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const app = express();
const PORT = process.env.PORT || ${port};

app.use(cors());
app.use(express.json());

// Health check
app.get('/api/health', (req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

// Auto-load routes from routes/ directory
const routesDir = path.join(__dirname, 'routes');
if (fs.existsSync(routesDir)) {
  const files = fs.readdirSync(routesDir).filter(f => f.endsWith('.js'));
  for (const file of files) {
    const route = await import(\`./routes/\${file}\`);
    // e.g. products.js -> /api/products
    const routeName = file.replace('.js', '');
    app.use(\`/api/\${routeName}\`, route.default || route);
  }
}

// 404 handler
app.use('/api', (req, res) => {
  res.status(404).json({ error: 'Not found' });
});

app.listen(PORT, '0.0.0.0', () => {
  console.log(\`Backend running on port \${PORT}\`);
});
`;
}

/**
 * Returns base files for a fullstack project.
 * @param port Frontend port (Vite)
 * @param backendPort Backend port (Express)
 */
export function getFullstackBaseFiles(port: number, backendPort: number): Record<string, string> {
  return {
    'package.json': rootPackageJson(),
    'frontend/package.json': frontendPackageJson(),
    'frontend/vite.config.js': viteConfig(port, backendPort),
    'frontend/index.html': indexHtml(),
    'frontend/src/main.jsx': mainJsx(),
    'frontend/src/index.css': indexCss,
    'backend/package.json': backendPackageJson(),
    'backend/server.js': backendServerJs(backendPort),
  };
}

/**
 * Build a complete ProjectFile[] for a fullstack project.
 * @param aiFiles Files generated by AI (may have frontend/ or backend/ prefixes)
 * @param port Frontend port
 * @param backendPort Backend port
 */
export function buildFullstackProjectFiles(
  aiFiles: Record<string, string>,
  port: number,
  backendPort: number,
): ProjectFile[] {
  const base = getFullstackBaseFiles(port, backendPort);
  const allFiles: Record<string, string> = { ...base, ...aiFiles };

  const langMap: Record<string, string> = {
    js: 'javascript', jsx: 'javascript', ts: 'typescript', tsx: 'typescript',
    html: 'html', css: 'css', json: 'json', md: 'markdown',
  };

  return Object.entries(allFiles).map(([filePath, content]) => ({
    path: filePath,
    content,
    language: langMap[filePath.split('.').pop() || ''] || 'text',
  }));
}

/**
 * Parse AI output into a file map for fullstack projects.
 * AI may output files with frontend/ or backend/ prefixes.
 */
export function parseFullstackFileMap(output: string): Record<string, string> {
  const jsonMatch = output.match(/\{[\s\S]*\}/);
  if (!jsonMatch) {
    return { 'frontend/src/App.jsx': output };
  }

  try {
    const parsed = JSON.parse(jsonMatch[0]);
    if (typeof parsed === 'object' && parsed !== null) {
      const files: Record<string, string> = {};
      for (const [key, value] of Object.entries(parsed)) {
        if (typeof value === 'string') {
          // Normalize paths: if no prefix, assume frontend
          let normalizedKey = key;
          if (!key.startsWith('frontend/') && !key.startsWith('backend/') &&
              !key.startsWith('package.json') && !key.startsWith('node_modules')) {
            // If it looks like a React component, put it in frontend/src/
            if (key.includes('App.') || key.includes('.jsx') || key.includes('.tsx')) {
              normalizedKey = key.startsWith('src/') ? `frontend/${key}` : `frontend/src/${key}`;
            }
          }
          files[normalizedKey] = value;
        }
      }
      if (Object.keys(files).length > 0) return files;
    }
  } catch {
    // Not valid JSON
  }

  return { 'frontend/src/App.jsx': output };
}
